[discord]
token = "TOKEN AQUI!" #coloque seu token aqui
# Não divida tokens, isso é bem pessoal

[ollama]
model = "emma" #coloque seu modelo de IA aqui!
# lembre-se de instalar um modelo, passo de 3 de preparação no README.md
