[discord]
token = "MTM1MTI4MTIzNzU3NDI4NzU4Mw.G2PZlv.u_aDEYz4tf93L5Vj7Wru_PQSmSj350YRkb0Fqw" #coloque seu token aqui
# Não divida tokens, isso é bem pessoal

[ollama]
model = "emma" #coloque seu modelo de IA aqui!
# lembre-se de instalar um modelo, passo de 3 de preparação no README.md